######################################################################
# Automatically generated by qmake (3.0) mie. nov. 9 15:06:11 2016
######################################################################

TEMPLATE = app
TARGET = F-35-Lightning
INCLUDEPATH += .

# Input
HEADERS += inc/ui/menuu.h
SOURCES += src/ui/main.cpp src/ui/menu.cpp

QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
